spring.application.name=personal-budget-api

spring.datasource.url=jdbc:postgresql://localhost:5432/budget
spring.datasource.username=budget
spring.datasource.password=budget

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.flyway.enabled=true

